// GENERATED by tools/generate-site.js — DO NOT EDIT.
// Single-source catalog value translations for cat and small-animal renderers.
// Derived from the independent catalog maps in the generator; regen to update.
window.FULUCK_CATALOG_I18N = {
  "colors": {
    "en": {
      "ゴールデンシェーデッド": "Golden Shaded",
      "ゴールデンシェーデッド＆ホワイト": "Golden Shaded & White",
      "シルバー&ホワイト（トリプルコート）": "Silver & White (Triple Coat)",
      "シルバーシェーデット": "Silver Shaded",
      "シルバーシェーデッド": "Silver Shaded",
      "シルバータビー": "Silver Tabby",
      "シルバータビー トリプルコート": "Silver Tabby, Triple Coat",
      "シルバータビー（トリプルコート）": "Silver Tabby (Triple Coat)",
      "シルバーパッチドタビー": "Silver Patched Tabby",
      "シルバー＆ホワイト トリプルコート": "Silver & White, Triple Coat",
      "シールポイント(ネヴァマスカレード)（トリプルコート）": "Seal Point (Neva Masquerade) (Triple Coat)",
      "チョコレートゴールデン ロングヘア": "Chocolate Golden Longhair",
      "チョコレートゴールデン(ロングヘア)": "Chocolate Golden (Longhair)",
      "チンチラゴールデン ロングヘア": "Chinchilla Golden Longhair",
      "ブラウンタビー トリプルコート": "Brown Tabby, Triple Coat",
      "ブラウンタビー&ホワイト": "Brown Tabby & White",
      "ブラウンタビー&ホワイト（トリプルコート）": "Brown Tabby & White (Triple Coat)",
      "ブラウンタビー＆ホワイト": "Brown Tabby & White",
      "ブラウンタビー（トリプルコート）": "Brown Tabby (Triple Coat)",
      "ブルー&ホワイト（トリプルコート）": "Blue & White (Triple Coat)",
      "ブルーパッチドタビー&ホワイト": "Blue Patched Tabby & White",
      "ブルーパッチドタビー&ホワイト（トリプルコート）": "Blue Patched Tabby & White (Triple Coat)",
      "ブルーパッチドタビー＆ホワイト": "Blue Patched Tabby & White",
      "ブルーリンクスポイント ネヴァマスカレード": "Blue Lynx Point Neva Masquerade",
      "ブルーリンクスポイント(ネヴァマスカレード)（トリプルコート）": "Blue Lynx Point (Neva Masquerade) (Triple Coat)",
      "ホワイト": "White",
      "ホワイト トリプルコート": "White, Triple Coat",
      "ホワイトソリッド（トリプルコート）": "Solid White (Triple Coat)",
      "ホワイト（トリプルコート）": "White (Triple Coat)",
      "レッドリンクスポイント": "Red Lynx Point",
      "レッドリンクスポイント トリプルコート": "Red Lynx Point, Triple Coat",
      "レッドリンクスポイント（トリプルコート）": "Red Lynx Point (Triple Coat)"
    },
    "zh": {
      "ゴールデンシェーデッド": "金渐层",
      "ゴールデンシェーデッド＆ホワイト": "金渐层加白",
      "シルバー&ホワイト（トリプルコート）": "银色加白（三层被毛）",
      "シルバーシェーデット": "银渐层",
      "シルバーシェーデッド": "银渐层",
      "シルバータビー": "银虎斑",
      "シルバータビー トリプルコート": "银虎斑 三层被毛",
      "シルバータビー（トリプルコート）": "银虎斑（三层被毛）",
      "シルバーパッチドタビー": "银玳瑁虎斑",
      "シルバー＆ホワイト トリプルコート": "银色加白 三层被毛",
      "シールポイント(ネヴァマスカレード)（トリプルコート）": "海豹重点色（涅瓦假面）（三层被毛）",
      "チョコレートゴールデン ロングヘア": "巧克力金渐层 长毛",
      "チョコレートゴールデン(ロングヘア)": "巧克力金渐层（长毛）",
      "チンチラゴールデン ロングヘア": "金吉拉金渐层 长毛",
      "ブラウンタビー トリプルコート": "棕虎斑 三层被毛",
      "ブラウンタビー&ホワイト": "棕虎斑加白",
      "ブラウンタビー&ホワイト（トリプルコート）": "棕虎斑加白（三层被毛）",
      "ブラウンタビー＆ホワイト": "棕虎斑加白",
      "ブラウンタビー（トリプルコート）": "棕虎斑（三层被毛）",
      "ブルー&ホワイト（トリプルコート）": "蓝色&白色（三层被毛）",
      "ブルーパッチドタビー&ホワイト": "蓝玳瑁虎斑加白",
      "ブルーパッチドタビー&ホワイト（トリプルコート）": "蓝玳瑁虎斑加白（三层被毛）",
      "ブルーパッチドタビー＆ホワイト": "蓝玳瑁虎斑加白",
      "ブルーリンクスポイント ネヴァマスカレード": "蓝色山猫重点色 涅瓦假面",
      "ブルーリンクスポイント(ネヴァマスカレード)（トリプルコート）": "蓝色山猫重点色（涅瓦假面）（三层被毛）",
      "ホワイト": "白色",
      "ホワイト トリプルコート": "白色 三层被毛",
      "ホワイトソリッド（トリプルコート）": "纯白色（三层被毛）",
      "ホワイト（トリプルコート）": "白色（三层被毛）",
      "レッドリンクスポイント": "红色山猫重点色",
      "レッドリンクスポイント トリプルコート": "红色山猫重点色 三层被毛",
      "レッドリンクスポイント（トリプルコート）": "红色山猫重点色（三层被毛）"
    }
  },
  "breeds": {
    "en": {
      "サイベリアン": "Siberian",
      "サイベリアン&ブリティッシュショートヘア": "Siberian × British Shorthair mix",
      "サイベリアンXブリティッシュショットヘア": "Siberian × British Shorthair mix",
      "サイベリアン×ブリティッシュ": "Siberian × British mix",
      "ブリティッシュショートヘア": "British Shorthair",
      "ブリティッシュロングヘア": "British Longhair",
      "ラグドール": "Ragdoll"
    },
    "zh": {
      "サイベリアン": "西伯利亚猫",
      "サイベリアン&ブリティッシュショートヘア": "西伯利亚×英短混血",
      "サイベリアンXブリティッシュショットヘア": "西伯利亚×英短混血",
      "サイベリアン×ブリティッシュ": "西伯利亚×英系混血",
      "ブリティッシュショートヘア": "英国短毛猫",
      "ブリティッシュロングヘア": "英国长毛猫",
      "ラグドール": "布偶猫"
    }
  },
  "smallAnimalSpecies": {
    "en": {
      "ウサギ": "Rabbit"
    },
    "zh": {
      "ウサギ": "兔"
    }
  },
  "smallAnimalBreeds": {
    "en": {
      "ネザーランドドワーフ": "Netherland Dwarf"
    },
    "zh": {
      "ネザーランドドワーフ": "荷兰侏儒兔"
    }
  },
  "smallAnimalColors": {
    "en": {},
    "zh": {}
  }
};
