const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const {parseFragment}=require('parse5');
const read=p=>fs.readFileSync(p,'utf8');
function nodes(html){let out=[];function visit(n){out.push(n);(n.childNodes||[]).forEach(visit)}visit(parseFragment(html));return out;}
function attr(n,k){return n.attrs?.find(x=>x.name===k)?.value;}
function runtime(lang='ja') { const ctx=vm.createContext({URLSearchParams,window:{location:{pathname:(lang==='ja'?'':'/'+lang)+'/kittens/2603-02736.html',search:'',hash:''}}});let s=read('nav.js').replace("\n  if (typeof module !== 'undefined' && module.exports) {",'\n globalThis.desktop=renderDesktopNav;globalThis.mobile=renderMobileNav;'+"\n  if (typeof module !== 'undefined' && module.exports) {");vm.runInContext(s,ctx);ctx.document={body:{getAttribute(){return null}},documentElement:{getAttribute(){return lang}},querySelectorAll(){return []}};return ctx;}
test('every locale has a direct desktop catalog entry and only one menu booking action',()=>{for(const lang of ['ja','en','zh']){const c=runtime(lang);for(const render of [c.desktop,c.mobile]){const all=nodes(render({path:'/kittens/2603-02736.html',hash:''}));const a=all.filter(n=>n.tagName==='a');assert.equal(a.filter(n=>attr(n,'href')?.startsWith('/booking.html')).length,1);assert(a.some(n=>attr(n,'href')===(lang==='ja'?'':'/'+lang)+'/kittens.html'&&attr(n,'class')?.includes('nav-catalog-direct')))}}});
test('homepage puts filter controls after the first kitten page',()=>{const s=read('index.html');assert(s.indexOf('data-home-catalog')>s.indexOf('END GENERATED HOMEPAGE KITTENS'));assert.match(s,/href="#home-kitten-filters"/);});
test('kitten detail routes reuse approved footage and load the background module',async()=>{const {ambientPage}=await import('../ambient-pages.mjs');for(const prefix of ['','/en','/zh']){assert.deepEqual(ambientPage(prefix+'/kittens/2603-02736.html')?.clips,['A','B','C']);const s=read((prefix?prefix.slice(1)+'/':'')+'kittens/2603-02736.html');assert.match(s,/ambient-motion\.mjs/);assert.match(s,/class="kitten-detail-back"/);}assert.equal(ambientPage('/admin/kittens/test.html'),null);});
test('legacy widget defers to an existing mobile bar even when added before its fetch resolves',async()=>{let existing=false,appended=0,resolve;const ctx=vm.createContext({location:{pathname:'/blog.html'},window:{FuluckKittenCatalog:{orderKittens:x=>x},addEventListener(){}},document:{querySelector(){return existing?{}:null},body:{appendChild(){appended++}},documentElement:{lang:'ja'},createElement(){return{classList:{add(){},remove(){}}}}},fetch:()=>new Promise(r=>resolve=r),console});vm.runInContext(read('cta-widget.js'),ctx);existing=true;resolve({ok:true,json:async()=>[]});await new Promise(r=>setImmediate(r));assert.equal(appended,0);});
