// admin-export.js — HTML code generation for kittens/parents/reviews
// Depends on: admin-core.js (data, getCoverPhoto), admin-images.js (t)

function generateKittensHTML() {
  var kittens = data.kittens.filter(function(k) { return k.group === 'c995680' && ['available','reserved'].indexOf(k.status) >= 0; });
  var html = '<!-- Generated by Admin Panel - Index Kittens Section -->\n';
  kittens.forEach(function(k) {
    var cover = getCoverPhoto(k);
    var statusClass = k.status === 'available' ? 'st-available' : 'st-reserved';
    var statusText = k.status === 'available' ? '販売中' : '商談中';
    var genderFull = k.gender === '♂' ? '♂ 男の子' : '♀ 女の子';
    var bMonth = k.birthday ? k.birthday.replace('-', '年') + '月生まれ' : '';
    html +=
'        <div class="kitten-card" data-status="' + k.status + '" data-price="' + k.price + '" data-birthday="' + k.birthday + '-01" data-images="" data-video="' + (k.video||'').replace(/"/g, '&quot;') + '" data-papa="' + (k.papa||'') + '" data-mama="' + (k.mama||'') + '" data-new="' + k.isNew + '" data-name="" data-breeder-id="' + k.breederId + '">\n' +
'          <div class="kitten-img">\n' +
'            <img src="' + cover + '" alt="子猫の写真" loading="lazy" style="width:100%;height:100%;object-fit:cover;">\n' +
'            <span class="kit-status ' + statusClass + '" data-i18n="kittens.' + k.status + '">' + statusText + '</span>' + (k.isNew ? '\n            <span class="kit-badge-new">NEW</span>' : '') + '\n' +
'          </div>\n' +
'          <div class="kitten-body">\n' +
'            <h3>' + k.breed + '</h3>\n' +
'            <p class="kit-meta">' + genderFull + ' ・ ' + k.color + '</p>\n' +
'            <p class="kit-meta">' + bMonth + '</p>' + (k.note ? '\n            <p class="kit-meta" style="font-size:11px;color:var(--text-note);">' + k.note + '</p>' : '') + '\n' +
'            <p class="kit-price">¥' + k.price.toLocaleString() + ' <span class="tax">（税込）</span></p>\n' +
'          </div>\n' +
'        </div>\n';
  });

  document.getElementById('generatedCode').textContent = html;
  document.getElementById('generatedCodeTitle').textContent = '子猫セクション HTML（index.html用）';
  document.getElementById('generatedCodeArea').style.display = 'block';
  showToast(t('HTMLコードを生成しました','已生成HTML代码'), 'success');
}

function generateParentsHTML() {
  var html = '<!-- Generated by Admin Panel - Parents Section -->\n';
  data.parents.forEach(function(p) {
    var cover = getCoverPhoto(p);
    var roleClass = p.role === 'パパ猫' ? 'role-papa' : 'role-mama';
    html +=
'        <div class="parent-card" onclick="openParentModal(this)" data-name="' + p.name + '" data-breed="' + p.breed + '" data-gender="' + p.gender + '" data-role="' + p.role + '" data-age="' + p.age + '" data-color="' + p.color + '" data-tested="' + p.tested + '" style="position:relative;">\n' +
'          <span class="health-tag tag-good" style="position:absolute;top:8px;right:8px;font-size:11px;padding:2px 8px;">✓ 遺伝子検査済</span>\n' +
'          <img src="' + cover + '" alt="' + p.name + '" loading="lazy" style="width:100%;height:100%;object-fit:cover;border-radius:var(--radius-lg) var(--radius-lg) 0 0;">\n' +
'          <div class="parent-body">\n' +
'            <h3>' + p.name + '</h3>\n' +
'            <p>' + p.breed + ' ・ ' + p.gender + ' ・ ' + p.color + '</p>\n' +
'            <p style="font-size:12px;color:var(--text-note);">' + p.age + '</p>\n' +
'            <span class="parent-role ' + roleClass + '">' + p.role + '</span>\n' +
'          </div>\n' +
'        </div>\n';
  });

  document.getElementById('generatedCode').textContent = html;
  document.getElementById('generatedCodeTitle').textContent = '親猫セクション HTML（parents.html用）';
  document.getElementById('generatedCodeArea').style.display = 'block';
  showToast(t('HTMLコードを生成しました','已生成HTML代码'), 'success');
}

function generateReviewsHTML() {
  var html = '<!-- Generated by Admin Panel - Reviews Section -->\n';
  data.reviews.forEach(function(r) {
    html +=
'        <div class="review-card">\n' +
'          <div class="review-header">\n' +
'            <div class="review-stars">★★★★★</div>\n' +
'            <span class="review-platform">みんなの子猫ブリーダー</span>\n' +
'          </div>\n' +
'          <p class="review-body">' + r.body + '</p>\n' +
'          <div class="review-footer">\n' +
'            <p class="review-author">— ' + r.region + ' ' + r.author + '（' + r.date + '）</p>\n' +
'            <span class="review-verified">✓ 認証済みレビュー</span>\n' +
'          </div>\n' +
'        </div>\n';
  });

  document.getElementById('generatedCode').textContent = html;
  document.getElementById('generatedCodeTitle').textContent = 'レビューセクション HTML（reviews.html用）';
  document.getElementById('generatedCodeArea').style.display = 'block';
  showToast(t('HTMLコードを生成しました','已生成HTML代码'), 'success');
}

function copyGeneratedCode() {
  var code = document.getElementById('generatedCode').textContent;
  navigator.clipboard.writeText(code).then(function() {
    showToast(t('コピーしました','已复制'), 'success');
  }).catch(function() {
    var ta = document.createElement('textarea');
    ta.value = code;
    document.body.appendChild(ta);
    ta.select();
    document.execCommand('copy');
    document.body.removeChild(ta);
    showToast(t('コピーしました','已复制'), 'success');
  });
}
